version: 0.0
os: linux	
files:	
  - source: dist/cicd-pipeline-train-schedule-git  
    destination: /var/www/html/	    
hooks:	
  BeforeInstall:	 
    - location: /scripts/install_dependencies	   
      timeout: 300	          
    - location: /scripts/start_server	    
      timeout: 300	     
            

