version: 0.2

phases:
    install:
        runtime-versions:
            nodejs: 16
        commands:
            - echo Executing Install phase
            # Install dependencies needed for running tests
            # apt install npm
    pre_build:
        commands:
            - echo Executing pre build phase
    build:
        commands:
            - echo Executing Build phase
    post_build:
        commands:
            - echo Executing post build phase
artifacts:
  files: 
    - '**/*'
    - appspec.yml
    - 'scripts/**/*'
   
